-- DO NOT EDIT THIS FILE
bLogs.Config={}local
_=bLogs.Config
_.DefaultLanguage="russian"_.MaxPermitted={"admin"}_.ChatCommand="!blogs"_.AllowConsoleCommand=!!1
_.FunctionMenuKey=!1
_.LogsPerPage=60
_.EntityNames={["weapon_zm_improvised"]="Crowbar",["weapon_zm_carry"]="Magneto Stick",["weapon_ttt_unarmed"]="Holstered"}_.ForcedModules={["Trouble in Terrorist Town"]=!1,["Cinema"]=!1,["DarkRP"]=!1,["Murder"]=!1}_.BlacklistedCommands={ulx={"noclip"},darkrp={"/","/ooc"}}